#!/usr/bin/env node
/**
 * Reads SVG avatars from a source directory and generates
 * `packages/views/common/avatar-set.ts` containing data-URI strings
 * for each, so the runtime has zero filesystem / network dependency.
 *
 * Usage: node scripts/build-avatars.mjs [source_dir]
 *   default source_dir = ./assets/agent-avatars-lorelei/avatars
 *
 * Each entry: { id: filename-without-ext, name: same, url: data:image/svg+xml;utf8,... }
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, basename, extname } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(fileURLToPath(import.meta.url), "../..");
const sourceDir =
  process.argv[2] ?? join(repoRoot, "assets", "agent-avatars-lorelei", "avatars");
const outputFile = join(repoRoot, "packages/views/common/avatar-set.ts");

console.log(`[build-avatars] reading from: ${sourceDir}`);
const stat = statSync(sourceDir);
if (!stat.isDirectory()) {
  console.error(`[build-avatars] source is not a directory: ${sourceDir}`);
  process.exit(1);
}

const files = readdirSync(sourceDir)
  .filter((f) => f.toLowerCase().endsWith(".svg"))
  .sort((a, b) => a.localeCompare(b));

if (files.length === 0) {
  console.error(`[build-avatars] no SVG files found in ${sourceDir}`);
  process.exit(1);
}

const entries = files.map((file) => {
  const id = basename(file, extname(file));
  // Sanitize raw SVG: strip leading XML declaration and any leading whitespace
  // before <svg, since some encoders emit them inconsistently and they bloat
  // the data-URI without rendering value.
  const raw = readFileSync(join(sourceDir, file), "utf8")
    .replace(/^﻿/, "")
    .replace(/^<\?xml[^?]*\?>/, "")
    .replace(/^\s+/, "");
  // utf8 encoding (vs base64) is cheaper for SVGs which are already text.
  const url = `data:image/svg+xml;utf8,${encodeURIComponent(raw)}`;
  return { id, name: id, url };
});

const banner = `// Auto-generated by scripts/build-avatars.mjs — DO NOT EDIT BY HAND.
// Source: local Lorelei SVG avatar assets
// To regenerate: \`node scripts/build-avatars.mjs\`

`;

const body =
  `export interface AvatarPreset {\n` +
  `  /** Stable identifier (filename without extension), e.g. "Aspen". */\n` +
  `  id: string;\n` +
  `  /** Display name, currently same as id. */\n` +
  `  name: string;\n` +
  `  /** data:image/svg+xml;utf8,... — embed directly as <img src> or avatar_url. */\n` +
  `  url: string;\n` +
  `}\n\n` +
  `export const AVATAR_SET: AvatarPreset[] = [\n` +
  entries
    .map(
      (e) =>
        `  { id: ${JSON.stringify(e.id)}, name: ${JSON.stringify(e.name)}, url: ${JSON.stringify(e.url)} },`,
    )
    .join("\n") +
  `\n];\n\n` +
  `export const AVATAR_SET_SIZE = ${entries.length};\n`;

writeFileSync(outputFile, banner + body, "utf8");
console.log(
  `[build-avatars] wrote ${entries.length} avatars to ${outputFile} (${Math.round(banner.length + body.length / 1024)} KB approx in TS)`,
);
