#!/usr/bin/env node
/**
 * Reads local avatar assets from a source directory and generates
 * `packages/views/common/avatar-set.ts` containing data-URI strings
 * for each, so the runtime has zero filesystem / network dependency.
 *
 * Usage: node scripts/build-avatars.mjs [source_dir]
 *   default source_dir = ./assets/origin-agent-avatars/avatars
 *
 * Each entry: { id: filename-without-ext, name: display name, url: data:image/... }
 */

import { readdirSync, readFileSync, writeFileSync, statSync } from "node:fs";
import { join, basename, dirname, extname } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), "..");
const sourceDir =
  process.argv[2] ?? join(repoRoot, "assets", "origin-agent-avatars", "avatars");
const outputFile = join(repoRoot, "packages/views/common/avatar-set.ts");
const SUPPORTED_EXTENSIONS = new Set([".png", ".svg"]);

console.log(`[build-avatars] reading from: ${sourceDir}`);
const stat = statSync(sourceDir);
if (!stat.isDirectory()) {
  console.error(`[build-avatars] source is not a directory: ${sourceDir}`);
  process.exit(1);
}

const files = readdirSync(sourceDir)
  .filter((f) => SUPPORTED_EXTENSIONS.has(extname(f).toLowerCase()))
  .sort((a, b) => a.localeCompare(b));

if (files.length === 0) {
  console.error(`[build-avatars] no supported avatar files found in ${sourceDir}`);
  process.exit(1);
}

function toDisplayName(id) {
  const numbered = id.match(/^origin-agent-(\d+)$/);
  if (numbered) return `Origin ${numbered[1]}`;
  return id
    .split(/[-_]+/)
    .filter(Boolean)
    .map((part) => part[0]?.toUpperCase() + part.slice(1))
    .join(" ");
}

function toDataUri(file) {
  const path = join(sourceDir, file);
  const ext = extname(file).toLowerCase();
  if (ext === ".svg") {
    const raw = readFileSync(path, "utf8")
      .replace(/^﻿/, "")
      .replace(/^<\?xml[^?]*\?>/, "")
      .replace(/^\s+/, "");
    return "data:image/svg+xml;utf8," + encodeURIComponent(raw);
  }
  if (ext === ".png") {
    return "data:image/png;base64," + readFileSync(path).toString("base64");
  }
  throw new Error(`Unsupported avatar extension: ${ext}`);
}

const entries = files.map((file) => {
  const id = basename(file, extname(file));
  return { id, name: toDisplayName(id), url: toDataUri(file) };
});

const banner = `// Auto-generated by scripts/build-avatars.mjs — DO NOT EDIT BY HAND.
// Source: local Origin avatar assets
// To regenerate: \`node scripts/build-avatars.mjs\`

`;

const body =
  `export interface AvatarPreset {\n` +
  `  /** Stable identifier (filename without extension), e.g. "Aspen". */\n` +
  `  id: string;\n` +
  `  /** Display name shown in toasts and debug surfaces. */\n` +
  `  name: string;\n` +
  `  /** data:image/... — embed directly as <img src> or avatar_url. */\n` +
  `  url: string;\n` +
  `}\n\n` +
  `export const AVATAR_SET: AvatarPreset[] = [\n` +
  entries
    .map(
      (e) =>
        `  { id: ${JSON.stringify(e.id)}, name: ${JSON.stringify(e.name)}, url: ${JSON.stringify(e.url)} },`,
    )
    .join("\n") +
  `\n];\n\n` +
  `export const AVATAR_SET_SIZE = ${entries.length};\n`;

writeFileSync(outputFile, banner + body, "utf8");
console.log(
  `[build-avatars] wrote ${entries.length} avatars to ${outputFile} (${Math.round(banner.length + body.length / 1024)} KB approx in TS)`,
);
